category: explainer
explainer_type: DAEdistill
distilled_predictor: <PEAL_BASE>/configs/diffae_experiments/predictors/dae_distill_predictor.yaml
use_clustering: true
clustering_strategy: highest_activation
num_attempts: 2
linesearch_factors: [2.0]