training          : <PEAL_BASE>/configs/training/sensitive_distillation.yaml
is_loaded         : False
continue_training : False
distill_from      : predictor
architecture      : torchvision_resnet18
data              : <PEAL_BASE>/configs/data/waterbirds256x256_sd3.yaml
task:
  criterions:
    ce     : 1.0
    l2     : 100.0
  output_type             : singleclass
  output_channels         : 2
  y_selection             : [prediction]