# python train_generator.py --config "<PEAL_BASE>/configs/didae_experiments/generators/square_diffusion_autoencoder.yaml"
# python run_component_analysis.py --config $PEAL_RUNS/square/diffusion_autoencoder/config.yaml --sd_config configs/didae_experiments/sparse_dictionaries/matryoshka_sae_default.yaml
# python run_component_analysis.py --config $PEAL_RUNS/square/diffusion_autoencoder/config.yaml --sd_config configs/didae_experiments/sparse_dictionaries/svd_default.yaml
# python run_component_analysis.py --config $PEAL_RUNS/square/diffusion_autoencoder/config.yaml --sd_config configs/didae_experiments/sparse_dictionaries/procrustes_sae_square.yaml
generator_type : DiffusionAutoencoder
category : generator
base_path : $PEAL_RUNS/square/diffusion_autoencoder
data: <PEAL_BASE>/configs/sce_experiments/data/square_generator.yaml
image_size: 64
batch_size: 100
save_every_samples: 20000
total_samples: 400001
encoder_dimensions : 512
encoder_path: $PEAL_RUNS/square/colora_confounding_colorb/classifier_all_attributes_resnet18/model.cpl
is_torchvision_resnet: true
sparse_dictionary: <PEAL_BASE>/configs/didae_experiments/sparse_dictionaries/matryoshka_sae_default.yaml