category: generator
generator_type: DiffusionGenerator
data: <PEAL_BASE>/configs/cfkd_fastdime_hq/data/imagenet_egyptian_cat_vs_persian_cat.yaml
base_path : $PEAL_RUNS/imagenet/stable_diffusion3_egyptian_cat_vs_persian_cat
shift: 1.0
