ending: .npz
n_components: 4
sparse_dictionaries_type: OrthogonalProcrustesDictionary
category: sparse_dictionaries
task:
  y_selection: [Blond_Hair, Male, Wearing_Hat, Eyeglasses]
  output_type: multiclass
  output_channels: 4
  criterions:
    bce: 1.0
    l2: 100.0