ending: .npz
n_components: 2
sparse_dictionaries_type: OrthogonalProcrustesDictionary
category: sparse_dictionaries
task:
  y_selection: [ClassA, ClassB]
  output_type: multiclass
  output_channels: 2
  criterions:
    bce: 1.0
    l2: 100.0