ending: .npz
n_components: 8
sparse_dictionaries_type: OrthogonalProcrustesDictionary
category: sparse_dictionaries
task:
  y_selection: [Blond_Hair, Male, Heavy_Makeup, Wearing_Lipstick, Wearing_Necktie, Attractive, Wearing_Hat, Eyeglasses]
  output_type: multiclass
  output_channels: 8
  criterions:
    bce: 1.0
    l2: 100.0