# python run_component_analysis.py --config configs/didae_experiments/generators/stable_diffusion_autoencoder_splice.yaml --sd_config configs/didae_experiments/sparse_dictionaries/splice_clip_vit_l_14_nico_bear_vs_dog.yaml
category: sparse_dictionaries
sparse_dictionaries_type: SpLICEDecomposition
clip_model: "clip:ViT-L/14"
vocabulary: laion
vocabulary_size: -1
l1_penalty: 0.15
solver: skl
component_strings: [bear, water]
opposite_component_strings: [dog, grass]
batch_size: 1
data: "<PEAL_BASE>/configs/didae_experiments/data/nico_bear_vs_dog_generator.yaml"
benchmark_ddpm_inversion: True