# python run_cfkd.py --config configs/tabular_experiments/adaptors/compass_cfkd_dice.yaml
batch_size                           :  8
min_train_samples                    :  8
mixing_ratio                         :  0.5
finetune_iterations                  :  5
max_validation_samples               :  100
continuous_learning                  :  "False"
replace_model                        :  True
explainer                            :  <PEAL_BASE>/configs/tabular_experiments/explainers/dice_compass.yaml
training                             :  <PEAL_BASE>/configs/tabular_experiments/training/symbolic_classifier.yaml
data                                 :  <PEAL_BASE>/configs/tabular_experiments/data/compass.yaml

test_data                            :  <PEAL_BASE>/configs/tabular_experiments/data/compass.yaml
student                              :  $PEAL_RUNS/compass/classifier_poisoned/model.cpl

teacher                              :
  type: "symbolic"
  model: peal_runs/compass/classifier_poisoned/model.cpl
  confounder_name: "African_American" # the user specifies to use 'being black' as the confounder


base_dir                             :  $PEAL_RUNS/compass/classifier_poisoned/cfkd

task:
  criterions:
    ce     : 1.0
  output_type             : multiclass
  output_channels         : 2
  y_selection             : [Target]
  x_selection             : [Number_of_Priors, score_factor, Age_Above_FourtyFive, Age_Below_TwentyFive, African_American, Asian, Hispanic, Native_American, Other, Female, Misdemeanor]
