# python train_predictor.py --config "<PEAL_BASE>/configs/predictors/imagenet_classifier.yaml"
training          : <PEAL_BASE>/configs/training/sensitive_distillation_imagenet.yaml
architecture      : torchvision_resnet18_imagenet
data              : <PEAL_BASE>/configs/data/imagenet.yaml
task:
  criterions:
    ce     : 1.0
  output_type             : singleclass
  output_channels         : 1000