distill_from      : predictor
training          : <PEAL_BASE>/configs/cfkd_fastdime_hq/training/latent_convexity_distillation.yaml
architecture      : torchvision_resnet18
task:
  criterions:
    ce     : 1.0
    l2     : 100.0
    lc     : 10.0
  output_type             : singleclass
  output_channels         : 2
  y_selection             : [prediction]