# python run_cfkd.py --config "<PEAL_BASE>/configs/diffae_experiments/adaptors/celeba1000x098_sdae_projection.yaml"
adaptor_type                         :  "ProjectionAdaptor"
category                             :  "adaptor"
test_data                            :  <PEAL_BASE>/configs/cfkd_experiments/data/celeba.yaml
student                              :  $PEAL_RUNS/celeba1k/Blond_Hair/dinov2_poisoned098/model.cpl
base_dir                             :  $PEAL_RUNS/celeba1k/Blond_Hair/dinov2_poisoned098/sdae_projection
projected_component_index_list       :  [1]
sparse_dictionary                    :  $PEAL_RUNS/celeba/diffusion_autoencoder/OrthogonalProcrustesDictionary/config.yaml

