"""
Write a standalone CFKD config for chosen DiDAE directions of a finished run.

DiDAE's step 9 writes <run>/cfkd_on_false_directions.yaml only for directions its
teacher rejected.  For the ImageNet DINOv3 probes the probe is its own teacher
(no oracle exists), so every direction comes back "true" and step 9 never runs.
This script builds the same config DiDAE would have built (see
DiDAE._run_cfkd_on_false_directions) for directions YOU name, and swaps the
teacher for the LLM-as-human teacher so the finetuning can run unattended.

usage:
  python utils/make_cfkd_on_directions_config.py \
      --run $PEAL_RUNS/imagenet_probes/fireboat_vs_lifeboat_dinov3_linear/openai_clip_rae_guided_g2_didae_msae \
      --directions 0 2 3 \
      --target_name "the type of boat: fireboat vs lifeboat (hull shape, deck equipment, crew)" \
      --confounder_name "a water jet / spray of water being pumped into the air" \
      --out configs/didae_experiments/adaptors/imagenet_fireboat_vs_lifeboat_dinov3_cfkd_waterjet_llmteacher.yaml
"""

import argparse, copy, os, yaml


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--run", required=True, help="finished DiDAE run dir (holds config.yaml)"
    )
    ap.add_argument(
        "--directions",
        type=int,
        nargs="+",
        required=True,
        help="direction_idx values from sweep_results.pt / direction_feedback.txt",
    )
    ap.add_argument("--target_name", required=True)
    ap.add_argument("--confounder_name", required=True)
    ap.add_argument("--subdir", default="cfkd_finetuning_llmteacher")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    cfg = yaml.safe_load(open(os.path.join(a.run, "config.yaml")))
    explainer = copy.deepcopy(cfg["explainer"])
    if isinstance(explainer, dict):
        explainer["component_bounds_scale"] = float(
            cfg.get("component_bounds_scale", 1.0)
        )
    n_dirs = max(2, len(a.directions))
    batch_size = max(1, (2 * int(cfg["batch_size"])) // n_dirs)

    out = {
        "adaptor_type": "CFKD",
        "batch_size": batch_size,
        "tracking_level": cfg["tracking_level"],
        "min_train_samples": cfg["min_train_samples"],
        "finetune_iterations": cfg["finetune_iterations"],
        "max_validation_samples": cfg["max_validation_samples"],
        "continuous_learning": cfg["continuous_learning"],
        # no confounder labels for ImageNet pairs -> no group accuracies
        "calculate_group_accuracies": bool(
            cfg.get("calculate_group_accuracies", False)
        ),
        "counterfactual_type": cfg["counterfactual_type"],
        "use_true_counterfactuals": cfg["use_true_counterfactuals"],
        "max_test_batches": cfg["max_test_batches"],
        "component_indices": list(a.directions),
        "data": cfg["data"],
        "test_data": cfg["test_data"],
        "student": cfg["student"],
        # LLM-as-human teacher (peal/teachers/llm2model_teacher.py) instead of the
        # probe judging itself
        "teacher": {
            "type": "llm",
            "target_name": a.target_name,
            "confounder_name": a.confounder_name,
            "batch_size": 16,
        },
        "generator": cfg["generator"],
        "sparse_dictionary": cfg["sparse_dictionary"],
        "base_dir": os.path.join(a.run, a.subdir),
        "task": cfg["task"],
        "training": cfg["training"],
        "explainer": explainer,
        "seed": cfg["seed"],
    }
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    with open(a.out, "w") as f:
        f.write(
            f"# Generated by utils/make_cfkd_on_directions_config.py from {a.run}/config.yaml\n"
            f"# directions {a.directions}; run with: python -u -W ignore run_cfkd.py --config <this file>\n"
        )
        yaml.safe_dump(out, f, sort_keys=False, default_flow_style=False)
    print("wrote", a.out, "batch_size", batch_size, "directions", a.directions)


if __name__ == "__main__":
    main()
