apptainer run --nv asyrp_container.sif python edit_images.py  \
--run_train                    \
--do_train 1                   \
--do_test 1                    \
--n_train_img 100              \
--n_test_img 32                \
--n_iter 5                     \
--bs_train 1                   \
--t_0 999                      \
--n_inv_step 50                \
--n_train_step 50              \
--n_test_step 50               \
--get_h_num 1                  \
--train_delta_block            \
--save_x0                      \
--use_x0_tensor                \
--lr_training 0.5              \
--clip_loss_w 1.0              \
--l1_loss_w 3.0                \
--add_noise_from_xt            \
--lpips_addnoise_th 1.2        \
--lpips_edit_th 0.33           \
--user_defined_t_edit 500       \
--user_defined_t_addnoise 200   \
--load_random_noise \
--config custom.yml         \
--edit_attr "smiling"              \
--sh_file_name "/home/sidney/workspace/peal/scripts/asyrp_train.sh"   \
--exp peal_runs/asyrp/implicit_function       \
--custom_train_dataset_dir "datasets/celeba/imgs"    \
--custom_test_dataset_dir "datasets/celeba/imgs"  \
--model_path peal_runs/ddpm_celebahq/final.pt