training          : <PEAL_BASE>/configs/didae_experiments/training/dae_distill_training.yaml
distill_from      : predictor
architecture      : torchvision_resnet18
task:
  criterions:
    l2     : 100.0
    bce    : 1.0
  output_type             : multiclass #singleclass #multiclass
  output_channels         : 1 #2 #1
  y_selection             : [prediction]