# python train_predictor.py --config "<PEAL_BASE>/configs/didae_experiments/predictors/nico_bear_vs_dog_poisoned098.yaml"
model_path        : $PEAL_RUNS/nico_bear_vs_dog/classifier_poisoned098
training          : <PEAL_BASE>/configs/didae_experiments/training/img_classifier_training_balanced.yaml
data              : <PEAL_BASE>/configs/didae_experiments/data/nico_bear_vs_dog_poisoned098.yaml
architecture      : torchvision_resnet18
task:
  criterions:
    ce     : 1.0
    l2     : 100.0
  output_type             : singleclass
  y_selection             : [label]
  output_channels         : 2
