# python train_predictor.py --config "<PEAL_BASE>/configs/didae_experiments/predictors/waterbirds_openclip_linear.yaml"
model_path        : $PEAL_RUNS/waterbirds/openclip_natural
training          : <PEAL_BASE>/configs/didae_experiments/training/img_classifier_balanced.yaml
data              : <PEAL_BASE>/configs/didae_experiments/data/waterbirds.yaml
architecture      : torchvision_open_clip
continue_training : True
only_last_layer   : True
task:
  criterions:
    ce     : 1.0
    l2     : 100.0
  output_type             : singleclass
  y_selection             : [y]
  output_channels         : 2