# python run_adaptor.py --config "<PEAL_BASE>/configs/didae_experiments/adaptors/funnynodules1kx098_didae_projection.yaml"
adaptor_type                         :  "ProjectionAdaptor"
category                             :  "adaptor"
data                                 :  <PEAL_BASE>/configs/cfkd_experiments/data/funnynodules1k_poisoned098.yaml
test_data                            :  <PEAL_BASE>/configs/cfkd_experiments/data/funnynodules_unpoisoned.yaml
base_model_config                    :  $PEAL_RUNS/funnynodules1k/internalstructure_confounding_roundness/torchvision/foundation_poisoned098/config.yaml
base_dir                             :  $PEAL_RUNS/funnynodules1k/internalstructure_confounding_roundness/torchvision/foundation_poisoned098/didae_projection
projected_component_index_list       :  [0]
sparse_dictionary                    :  $PEAL_RUNS/funnynodules/diffusion_autoencoder/OrthogonalProcrustesDictionary/config.yaml
