config_name : ArchitectureConfig
layers : [
  {config_name: FCConfig, num_neurons: 64, dropout: 0.0},
  {config_name: FCConfig, num_neurons: 64, dropout: 0.0},
]
#layers : [
#  [fc, 512, 0.25],
#  [fc, 512, 0.5]
#]
activation              : ReLU