adaptor_type: CFKD
category: adaptor
batch_size: 200
tracking_level: 5
min_train_samples: 800
finetune_iterations: 1
max_validation_samples: 200
continuous_learning: finetune
calculate_group_accuracies: true
calculate_explainer_stats: true
explainer: <PEAL_BASE>/configs/didae_experiments/explainers/dae_distill_ddpm.yaml
training: <PEAL_BASE>/configs/cfkd_experiments/training/img_finetuning.yaml
data: <PEAL_BASE>/configs/didae_experiments/seeds/celeba1k_Blond_Hair_classifier_poisoned098_data_seed3.yaml
test_data: <PEAL_BASE>/configs/cfkd_experiments/data/celeba.yaml
student: $PEAL_RUNS/celeba1k/Blond_Hair/classifier_poisoned098_seed3/model.cpl
teacher: $PEAL_RUNS/celeba/Blond_Hair/classifier_unpoisoned_seed3/model.cpl
generator: $PEAL_RUNS/celeba/diffusion_autoencoder_openai_clip_vit_l14_slim/config.yaml
sparse_dictionary: $PEAL_RUNS/celeba/diffusion_autoencoder_openai_clip_vit_l14/OrthogonalProcrustesDictionary/config.yaml
base_dir: $PEAL_RUNS/celeba1k/Blond_Hair/classifier_poisoned098_seed3/didae_cfkd
task:
  criterions:
    ce: 1.0
    l2: 100.0
  output_type: singleclass
  output_channels: 2
  y_selection:
  - Blond_Hair
seed: 3
