"""Sphinx configuration for the PEAL documentation.

Build locally with ``make html`` inside ``docs/`` (or
``sphinx-build -b html docs docs/_build/html`` from the repository root). The
API reference is generated by ``sphinx.ext.autosummary`` from the docstrings of
the ``peal`` package; third-party imports that are not installed on the build
machine are mocked so that the reference can be built without torch or a GPU
(this is what the GitHub Pages workflow relies on).
"""

import ast
import importlib
import re
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

# -- Project information -----------------------------------------------------

project = "PEAL"
author = "Sidney Bender and the PEAL contributors"
copyright = "2023-2026, Sidney Bender and the PEAL contributors"
# Single-sourced from peal/__init__.py, the same string setup.py publishes.
_init = (ROOT / "peal" / "__init__.py").read_text(encoding="utf-8")
release = re.search(r'^__version__ = "([^"]+)"', _init, re.M).group(1)
version = release

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "myst_parser",
]
# sphinx-autodoc-typehints is deliberately NOT used: autodoc's own
# `autodoc_typehints = "description"` already merges annotations into the
# Parameters sections, and the extension emits a "Failed guarded type import"
# warning for every module that annotates a parameter as a bare ``type``.

templates_path = ["_templates"]
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "README.md",
    # Non-Sphinx material that also lives under docs/.
    "agent_protocols",
    "paper_figures",
]
source_suffix = {".rst": "restructuredtext", ".md": "markdown"}

# -- autodoc / autosummary ---------------------------------------------------

autosummary_generate = True
autosummary_ignore_module_all = False
autodoc_member_order = "bysource"
autodoc_typehints = "description"
autodoc_class_signature = "separated"
# Members are documented on the per-object pages that autosummary generates,
# not a second time on the module page; documenting them in both places makes
# Sphinx emit a "duplicate object description" warning for every one of them.
autodoc_default_options = {
    "undoc-members": True,
    "show-inheritance": True,
    # pydantic bookkeeping that every config class inherits; it says nothing
    # about the config and dumps the whole field map into the page.
    "exclude-members": "model_config,model_fields,model_computed_fields,"
    "model_post_init,model_extra,model_fields_set",
}

# Submodules left out of the API reference (none at the moment; add a module
# name here to hide it from the generated pages).
autosummary_context = {
    # pydantic bookkeeping, kept out of the per-class summary tables the same
    # way autodoc_default_options keeps it out of the detailed entries.
    "peal_skip_attributes": [
        "model_config",
        "model_fields",
        "model_computed_fields",
        "model_extra",
        "model_fields_set",
    ],
    "peal_skip_modules": [],
}
# Third-party classes that many PEAL modules subclass; keep their huge member
# lists out of the reference.
autodoc_inherit_docstrings = False

napoleon_numpy_docstring = True
napoleon_google_docstring = True
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = True
# Render a class "Attributes" section as an :ivar: field list rather than
# standalone .. attribute:: directives. Without this, an attribute described in
# the docstring and picked up again by autodoc's undoc-members is registered
# twice and Sphinx warns about a duplicate object description.
napoleon_use_ivar = True

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "torch": ("https://pytorch.org/docs/stable/", None),
}
intersphinx_timeout = 10

myst_enable_extensions = ["colon_fence", "deflist", "fieldlist"]
myst_heading_anchors = 3


def _third_party_imports():
    """Top-level import names used by the first-party ``peal`` package.

    Vendored code under ``peal/dependencies`` is not documented and is skipped.
    """
    names = set()
    package = ROOT / "peal"
    for path in package.rglob("*.py"):
        if "dependencies" in path.relative_to(package).parts:
            continue
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except (SyntaxError, UnicodeDecodeError):
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    names.add(alias.name.split(".")[0])
            elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
                names.add(node.module.split(".")[0])
    names.discard("peal")
    return sorted(names)


def _missing_modules(names):
    """The subset of ``names`` that cannot be imported on this machine."""
    missing = []
    for name in names:
        if name in sys.builtin_module_names:
            continue
        try:
            importlib.import_module(name)
        except BaseException:  # noqa: BLE001 - anything means "mock it"
            missing.append(name)
    return missing


# Everything the package imports but this machine lacks (torch on a bare CI
# runner, omegaconf/captum for the optional generators, the RAEv2 clone, ...)
# is replaced by a mock so that autodoc can still import every module.
autodoc_mock_imports = _missing_modules(_third_party_imports())
if os.environ.get("PEAL_DOCS_VERBOSE"):
    print("[peal docs] mocked imports:", autodoc_mock_imports)

# -- Options for HTML output -------------------------------------------------

html_theme = "furo"
html_title = "PEAL"
html_static_path = ["_static"]
html_theme_options = {
    "source_repository": "https://github.com/Explainable-AI-Berlin/pytorch_explain_and_adapt_library",
    "source_branch": "master",
    "source_directory": "docs/",
}
