# python train_predictor.py --config configs/tabular_experiments/models/german_classifier_unpoisoned.yaml
model_path        : $PEAL_RUNS/german/classifier_unpoisoned
data              : <PEAL_BASE>/configs/tabular_experiments/data/german.yaml
training          : <PEAL_BASE>/configs/tabular_experiments/training/symbolic_classifier.yaml
architecture      : <PEAL_BASE>/configs/tabular_experiments/architectures/symbolic2vector.yaml
task:
  criterions:
    ce     : 1.0
  output_type             : singleclass
  output_size             : 2
  y_selection             : [Target]
